/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Admin
 */
public class Admin extends javax.swing.JFrame {

    /**
     * //Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jm_GioiThieu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        j_khuyenmai = new javax.swing.JMenuItem();
        jM_Thoat = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jm_luong = new javax.swing.JMenuItem();
        j_khachhang = new javax.swing.JMenuItem();
        jm_qlsanpaham = new javax.swing.JMenuItem();
        jm_ttdathang = new javax.swing.JMenuItem();
        j_Nhanvien = new javax.swing.JMenu();
        j_ttNhanvien = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jm_Thongke = new javax.swing.JMenuItem();
        jmenu_doanhthu = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        j_thanhtoan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jm_GioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Information.png"))); // NOI18N
        jm_GioiThieu.setText("Thông Tin");

        jMenuItem1.setText("Gioi Thiệu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jm_GioiThieu.add(jMenuItem1);

        j_khuyenmai.setText("Chương trình khuyến mãi");
        j_khuyenmai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_khuyenmaiActionPerformed(evt);
            }
        });
        jm_GioiThieu.add(j_khuyenmai);

        jM_Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Cancel.jpg"))); // NOI18N
        jM_Thoat.setText("Thoát");
        jm_GioiThieu.add(jM_Thoat);

        jMenuBar1.add(jm_GioiThieu);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Contact-icon.png"))); // NOI18N
        jMenu3.setText("Admin");

        jm_luong.setText("Lương Nhân Viên");
        jm_luong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_luongActionPerformed(evt);
            }
        });
        jMenu3.add(jm_luong);

        j_khachhang.setText("Khách Hàng");
        j_khachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_khachhangActionPerformed(evt);
            }
        });
        jMenu3.add(j_khachhang);

        jm_qlsanpaham.setText(" QL Sản Phẩm");
        jm_qlsanpaham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_qlsanpahamActionPerformed(evt);
            }
        });
        jMenu3.add(jm_qlsanpaham);

        jm_ttdathang.setText("Thông Tin Đặt Hàng");
        jm_ttdathang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_ttdathangActionPerformed(evt);
            }
        });
        jMenu3.add(jm_ttdathang);

        jMenuBar1.add(jMenu3);

        j_Nhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Contact-icon.png"))); // NOI18N
        j_Nhanvien.setText("Nhân Viên");

        j_ttNhanvien.setText("Thông Tin Nhân Viên");
        j_ttNhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_ttNhanvienActionPerformed(evt);
            }
        });
        j_Nhanvien.add(j_ttNhanvien);

        jMenuBar1.add(j_Nhanvien);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Health_Insurance-512.png"))); // NOI18N
        jMenu4.setText("Báo Cáo");

        jm_Thongke.setText("Thống Kê");
        jm_Thongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_ThongkeActionPerformed(evt);
            }
        });
        jMenu4.add(jm_Thongke);

        jmenu_doanhthu.setText("Doanh Thu");
        jmenu_doanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_doanhthuActionPerformed(evt);
            }
        });
        jMenu4.add(jmenu_doanhthu);

        jMenuBar1.add(jMenu4);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Contact-icon.png"))); // NOI18N
        jMenu1.setText("Khách Hàng");

        j_thanhtoan.setText("Thanh Toán");
        j_thanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_thanhtoanActionPerformed(evt);
            }
        });
        jMenu1.add(j_thanhtoan);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j_ttNhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_ttNhanvienActionPerformed
       TTNhanVien tt= new TTNhanVien();
       tt.setVisible(true);
    }//GEN-LAST:event_j_ttNhanvienActionPerformed

    private void j_khachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_khachhangActionPerformed
        TTKhachHang kh= new TTKhachHang();
        kh.setVisible(true);
    }//GEN-LAST:event_j_khachhangActionPerformed

    private void jm_qlsanpahamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_qlsanpahamActionPerformed
       QLSanPham sp= new QLSanPham();
       sp.setVisible(true);
    }//GEN-LAST:event_jm_qlsanpahamActionPerformed

    private void jmenu_doanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_doanhthuActionPerformed
      DoanhThu dt= new DoanhThu();
      dt.setVisible(true);
    }//GEN-LAST:event_jmenu_doanhthuActionPerformed

    private void jm_ThongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_ThongkeActionPerformed
        ThongKe tk= new ThongKe();
        tk.setVisible(true);
    }//GEN-LAST:event_jm_ThongkeActionPerformed

    private void jm_ttdathangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_ttdathangActionPerformed
       TTDaHang dh= new TTDaHang();
       dh.setVisible(true);
    }//GEN-LAST:event_jm_ttdathangActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FormGioiThieu gt= new FormGioiThieu();
        gt.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void j_khuyenmaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_khuyenmaiActionPerformed
       CTKhuyenMai km= new CTKhuyenMai();
       km.setVisible(true);
    }//GEN-LAST:event_j_khuyenmaiActionPerformed

    private void jm_luongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_luongActionPerformed
        QLNhanVien ql= new QLNhanVien();
        ql.setVisible(true);
    }//GEN-LAST:event_jm_luongActionPerformed

    private void j_thanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_thanhtoanActionPerformed
       ThanhToan tt= new ThanhToan();
       tt.setVisible(true);
    }//GEN-LAST:event_j_thanhtoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jM_Thoat;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu j_Nhanvien;
    private javax.swing.JMenuItem j_khachhang;
    private javax.swing.JMenuItem j_khuyenmai;
    private javax.swing.JMenuItem j_thanhtoan;
    private javax.swing.JMenuItem j_ttNhanvien;
    private javax.swing.JMenu jm_GioiThieu;
    private javax.swing.JMenuItem jm_Thongke;
    private javax.swing.JMenuItem jm_luong;
    private javax.swing.JMenuItem jm_qlsanpaham;
    private javax.swing.JMenuItem jm_ttdathang;
    private javax.swing.JMenuItem jmenu_doanhthu;
    // End of variables declaration//GEN-END:variables
}
