/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ThongKe extends javax.swing.JFrame {
    ResultSet rs, rsTK, rsInfoEmp, rsSPBan;
    Connection con;
    PreparedStatement ps, psTK, psSPBan;
    DefaultTableModel tblModel;
    Vector row, vecTK, vecSPBan;
    SimpleDateFormat ft = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat time = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy");
    NumberFormat formatter = new DecimalFormat("#,###");
    NumberFormat nft = new DecimalFormat("#,###");
    List<String> lsTenSP = new ArrayList<>();
    /**
     * Creates new form ThongKe
     */
    public ThongKe() {
        initComponents();
        bt_in.setEnabled(false);
        tblModel = new DefaultTableModel();
        tblModel.addColumn("ID");
        tblModel.addColumn("Tên");
        tblModel.addColumn("Giá");
        tblModel.addColumn("Loại");
        tblModel.addColumn("Số lượng");
//        tblModel.addColumn("Thành tiền");
        j_thongke.setModel(tblModel);
        loadBangSP();
        loadCBTK();
    }
    public void loadBangSP() {
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/qlqcf", "root", "2509");
            ps = con.prepareStatement("select * from qlqcf.chitietdathang join dathang on chitietdathang.MaDH=dathang.MaDH"
                    + " join sanpham on chitietdathang.MaSP=sanpham.MaSP Order by chitietdathang.MaDH DESC");
            rs = ps.executeQuery();
            int price, quantity, into;
            while (rs.next()) {
                row = new Vector();
                price = Integer.parseInt(rs.getString("GíaSP"));
                quantity = Integer.parseInt(rs.getString("SoLuong"));
                into = price * quantity;
                row.add(rs.getString("MaDH"));
                row.add(rs.getString("TenSP"));
                row.add(rs.getString("GíaSP"));
                row.add(rs.getString("MaLSP"));
                row.add(rs.getString("SoLuong"));
                tblModel.addRow(row);
            }
            j_thongke.setModel(tblModel);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Lỗi 101:: Không thể kết nối đến máy chủ");
        }
    }
    public void loadCBTK() {
        lsTenSP.add("CAPPUCCINO");
        lsTenSP.add("Cam ép");
        lsTenSP.add("Cà phê đá");
        lsTenSP.add("Cà phê sửa đá");
        lsTenSP.add("ESPRESSO MILK");
        lsTenSP.add("Sinh tố thập cẩm");
        lsTenSP.add("Trà đào");
        cb_tk.removeAllItems();
        for(String tensp: lsTenSP){
            cb_tk.addItem(tensp);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cb_tk = new javax.swing.JComboBox<>();
        tf_soluong = new javax.swing.JTextField();
        tf_gia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bt_timkiem = new javax.swing.JButton();
        bt_lammoi = new javax.swing.JButton();
        bt_in = new javax.swing.JButton();
        bt_sanpham = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        j_thongke = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thống Kê"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Sản Phẩn Đã Bán:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Tổng Số Lượng: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Tổng Gía: ");

        cb_tk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Ly");

        jLabel5.setText("VNĐ");

        bt_timkiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_timkiem.setForeground(new java.awt.Color(0, 153, 153));
        bt_timkiem.setText("Tìm Kiếm");
        bt_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_timkiemActionPerformed(evt);
            }
        });

        bt_lammoi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_lammoi.setForeground(new java.awt.Color(0, 204, 153));
        bt_lammoi.setText("Làm Mới");
        bt_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_lammoiActionPerformed(evt);
            }
        });

        bt_in.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_in.setForeground(new java.awt.Color(0, 102, 102));
        bt_in.setText("IN");
        bt_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inActionPerformed(evt);
            }
        });

        bt_sanpham.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_sanpham.setForeground(new java.awt.Color(204, 0, 0));
        bt_sanpham.setText("Sản Phẩm Bán Nhiều Nhất");
        bt_sanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sanphamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addComponent(cb_tk, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_in, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(bt_timkiem))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(tf_gia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_lammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_sanpham))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(50, 50, 50)
                        .addComponent(tf_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_soluong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(cb_tk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(bt_in)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_lammoi)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_timkiem)
                    .addComponent(jLabel6)
                    .addComponent(bt_sanpham))
                .addGap(78, 78, 78))
        );

        j_thongke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(j_thongke);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_timkiemActionPerformed
       tblModel.getDataVector().removeAllElements();
        String s1 = (String) cb_tk.getSelectedItem();
        if (cb_tk.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Tên sản phẩm không được để trống.");
            bt_in.setEnabled(false);
        } else {
            try {

                psTK = con.prepareStatement("select * from qlqcf.chitietdathang join dathang on chitietdathang.MaDH=dathang.MaDH"
                        + " join sanpham on chitietdathang.MaSP = sanpham.MaSP where TenSP=?");
                psTK.setString(1, (String) cb_tk.getSelectedItem());
                rsTK = psTK.executeQuery();
                if (rsTK.next()) {
                    psTK = con.prepareStatement("select * from qlqcf.chitietdathang join dathang on chitietdathang.MaDH=dathang.MaDH"
                            + " join sanpham on chitietdathang.MaSP = sanpham.MaSP where TenSP=?");
                    psTK.setString(1, (String) cb_tk.getSelectedItem());
                    rsTK = psTK.executeQuery();
                    while (rsTK.next()) {
                        vecTK = new Vector();
                        vecTK.add(rsTK.getString("MaDH"));
                        vecTK.add(rsTK.getString("TenSP"));
                        vecTK.add(rsTK.getString("GíaSP"));
                        vecTK.add(rsTK.getString("MaLSP"));
                        vecTK.add(rsTK.getString("SoLuong"));
                        tblModel.addRow(vecTK);
                    }
                    j_thongke.setModel(tblModel);
                } else {
                    JOptionPane.showMessageDialog(null, "Không tìm được sản phẩm");
                    loadBangSP();
                }
            } catch (Exception e) {
            }
            int line = j_thongke.getRowCount();
            int tong = 0, tinhtien = 0;
            for (int i = 0; i < line; i++) {
                int SL = Integer.parseInt((String) j_thongke.getValueAt(i, 4));
                int tien = Integer.parseInt((String) j_thongke.getValueAt(i, 2));
                tong += SL;
                tinhtien += tien;
//                spQuantity.setValue(quanTotal);
//            }
            }
            tf_gia.setText(String.valueOf(nft.format(tinhtien)));
            tf_soluong.setText(String.valueOf(tong));
            cb_tk.setSelectedIndex(-1);
        }
        bt_in.setEnabled(true);
    }//GEN-LAST:event_bt_timkiemActionPerformed

    private void bt_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_lammoiActionPerformed
        tf_soluong.setText("");
        tf_gia.setText("");
        cb_tk.setSelectedIndex(-1);
        tblModel.getDataVector().removeAllElements();
        loadBangSP();
        bt_in.setEnabled(false);
    }//GEN-LAST:event_bt_lammoiActionPerformed

    private void bt_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inActionPerformed
      File file = new File("ThongKe.txt");
        file.delete();
        //Viết vào file txt
        try {
            Date now = new Date();
            Writer b = new BufferedWriter(new OutputStreamWriter(new FileOutputStream("ThongKe.txt"), "UTF8"));
            b.write("\t\t\t\t\t\tTHE WIND COFFEE\r\n\r\n");
            b.write("\t\t\t\t\tĐịa chỉ: 32 Thanh Xuân, Thủ Dầu Một, Bình Dương\r\n");
            b.write("\t\t\t\t\t\tSĐT: 024876209\r\n");
            b.write("\t\t\t\t\tThời gian: " + time.format(now) + "\r\n\r\n");
            
            try {
                ps = con.prepareStatement("Select DISTINCT TenSP from qlqcf.sanpham");
                ps.setString(1, (String) cb_tk.getSelectedItem());
                rsInfoEmp = ps.executeQuery();
                if (rsInfoEmp.next()) {
                    b.write("Tên sản phẩm: " + rsInfoEmp.getString("TenSP") + "\r\n\r\n");
                }
            } catch (SQLException ex) {
            }
            b.write("--------------------------------------------------------------------------------------------------------------------------------\r\n");
            b.write("\t\t\t\tMã HĐ\tTên SP\t\t\t\tĐơn giá (VNĐ)\tLoại SP\t\tSố lượng (ly)\r\n");
            b.write("--------------------------------------------------------------------------------------------------------------------------------\r\n");

            int line = j_thongke.getRowCount();
            for (int i = 0; i < line; i++) {
                String s1 = (String) j_thongke.getValueAt(i, 0);
                String s2 = (String) j_thongke.getValueAt(i, 1);
                String s3 = (String) j_thongke.getValueAt(i, 2);
                String s4 = (String) j_thongke.getValueAt(i, 3);
                String s5 = (String) j_thongke.getValueAt(i, 4);
                b.write("\t\t\t\t" + s1 + "\t" + s2 + "\t\t\t" + s3 + "\t\t" + s4 + "\t\t" + s5 + "\t" + "\r\n");
            }
            b.write("--------------------------------------------------------------------------------------------------------------------------------\r\n");
            b.write("\t\t\t\t\t\t\t\t\t\t\t\tTổng số lượng: " + tf_soluong.getText() + "\r\n\r\n");
            b.write("\t\t\t\t\t\t\t\t\t\t\t\tTổng tiền: " + tf_gia.getText() + "\tVNĐ");
            b.close();
        } catch (IOException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        //Mở file txt
        Runtime run = Runtime.getRuntime();
        try {
            run.exec("notepad ThongKe.txt");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        bt_lammoiActionPerformed(evt);
    }//GEN-LAST:event_bt_inActionPerformed

    private void bt_sanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sanphamActionPerformed
       tblModel.getDataVector().removeAllElements();
        try {

            psSPBan = con.prepareStatement("select chitietdathang.MaSP, sanpham.GíaSP, sanpham.TenSP, sanpham.MaLSP, SUM(chitietdathang.SoLuong) as Tong"
                    + " from chitietdathang join sanpham on chitietdathang.MaSP=sanpham.MaSP Group by chitietdathang.MaSP,sanpham.GíaSP ,sanpham.TenSP,sanpham.MaLSP order by Tong DESC");
            rsSPBan = psSPBan.executeQuery();
            while (rsSPBan.next()) {
                vecSPBan = new Vector();
                vecSPBan.add(rsSPBan.getString("MaSP"));
                vecSPBan.add(rsSPBan.getString("TenSP"));
                vecSPBan.add(rsSPBan.getString("GíaSP"));
                vecSPBan.add(rsSPBan.getString("MaLSP"));
                vecSPBan.add(rsSPBan.getString("Tong"));
                tblModel.addRow(vecSPBan);
            }
            j_thongke.setModel(tblModel);
        } catch (Exception e) {
        }
        bt_in.setEnabled(true);
    }//GEN-LAST:event_bt_sanphamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_in;
    private javax.swing.JButton bt_lammoi;
    private javax.swing.JButton bt_sanpham;
    private javax.swing.JButton bt_timkiem;
    private javax.swing.JComboBox<String> cb_tk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable j_thongke;
    private javax.swing.JTextField tf_gia;
    private javax.swing.JTextField tf_soluong;
    // End of variables declaration//GEN-END:variables

    
}
