/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class TTDaHang extends javax.swing.JFrame {
    Connection con ;
    PreparedStatement ps;
    ResultSet rs, rsmadh, rsmasp, rstknv, rsctkm, rsmakh, rsSearch1, rsSearch2;
    DefaultTableModel tblModel = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    Vector row, rowSearch, vecmadh, vecmasp, vectknv, vecctkm, vecmakh;
    List<String> lsMaDH = new ArrayList<>();
    List<String> lsMaSP = new ArrayList<>();
    List<String> lsSoTaiKhoan = new ArrayList<>();
    List<String> lsTenKM = new ArrayList<>();
    List<String> lsTenKH = new ArrayList<>();
    
    /**
     * Creates new form TTDaHang
     */
    public TTDaHang() {
        initComponents();
        tblModel.addColumn("Mã đơn hàng");
        tblModel.addColumn("Mã sản phẩm");
        tblModel.addColumn("Mã khách hàng");
        tblModel.addColumn("Số lượng");
        tblModel.addColumn("CTKM");
        tblModel.addColumn("Thời gian");
        tblModel.addColumn("Ngày");
        tblModel.addColumn("Nhân viên");
        j_dathang.setModel(tblModel);
        ReloadTable();
        ReloadCombobox();
    }
     public void ReloadTable() {
        tblModel.getDataVector().removeAllElements();
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/qlqcf", "root", "2509");
            ps = con.prepareStatement("select * from qlqcf.chitietdathang join dathang on chitietdathang.MaDH=dathang.MaDH Order by chitietdathang.MaDH DESC");
            rs = ps.executeQuery();
            while (rs.next()) {
                row = new Vector();
                row.add(rs.getString("MaDH"));
                row.add(rs.getString("MaSP"));
                row.add(rs.getString("TenKH"));
                row.add(rs.getString("SoLuong"));
                row.add(rs.getString("TenKM"));
                row.add(rs.getString("ThoiGian"));
                row.add(rs.getString("NgayDH"));
                row.add(rs.getString("SoTaiKhoan"));
                tblModel.addRow(row);
            }
            j_dathang.setModel(tblModel);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Lỗi:: Không thể kết nối đến máy chủ");
        }
    }
      public void ReloadCombobox() {
        lsMaDH.add("HD0006");
        lsMaDH.add("HD0005");
        lsMaDH.add("HD0004");
        lsMaDH.add("HD0003");
        lsMaDH.add("HD0002");
        lsMaDH.add("HD0001");
        cb_madh.removeAllItems();
        for(String madh: lsMaDH){
            cb_madh.addItem(madh);
        }
        
        //
        lsMaSP.add("TD03");
        lsMaSP.add("TD02");
        lsMaSP.add("TD01");
        lsMaSP.add("ST02");
        lsMaSP.add("ST01");
        lsMaSP.add("ES03"); 
        lsMaSP.add("ES02");
        lsMaSP.add("ES01");
        lsMaSP.add("CF06");
        lsMaSP.add("CF05");
        lsMaSP.add("CF04");
        lsMaSP.add("CF03");
        lsMaSP.add("CF02");
        lsMaSP.add("CF01");
        lsMaSP.add("CE02");
        lsMaSP.add("CE01");
        lsMaSP.add("CA03");
        lsMaSP.add("CA02");
        lsMaSP.add("CA01");
        cb_masp.removeAllItems();
        for(String maSP: lsMaSP){
            cb_masp.addItem(maSP);
        }
        
        lsSoTaiKhoan.add("1");
        lsSoTaiKhoan.add("2");
        lsSoTaiKhoan.add("3");
        lsSoTaiKhoan.add("4");
        lsSoTaiKhoan.add("7");
        cb_tennv.removeAllItems();
        for(String maso: lsSoTaiKhoan){
            cb_tennv.addItem(maso);
        }
       //
       lsTenKM.add("Thẻ sinh viên");
       lsTenKM.add("Khách Hàng VIP");
       lsTenKM.add("Không có");
        cb_ctkm.removeAllItems();
        for(String km: lsTenKM){
            cb_ctkm.addItem(km);
            
        }
        //
        
        lsTenKH.add("100001");
        lsTenKH.add("100003");
        lsTenKH.add("Khách vãng lai");
        cb_makh.removeAllItems();
        for(String kh: lsTenKH){
            cb_makh.addItem(kh);
        }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cb_madh = new javax.swing.JComboBox<>();
        cb_masp = new javax.swing.JComboBox<>();
        cb_tennv = new javax.swing.JComboBox<>();
        cb_makh = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cb_ctkm = new javax.swing.JComboBox<>();
        bt_tk = new javax.swing.JButton();
        tf_thoigian = new javax.swing.JTextField();
        tf_ngay = new javax.swing.JTextField();
        bt_lm = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        j_dathang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("THÔNG TIN ĐẠT HÀNG"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("Mã Đơn Hàng:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Mã Sản Phẩm:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Nhân Viên:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Mã Khách Hàng:");

        cb_madh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cb_masp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cb_tennv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cb_makh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Chương Trình Khuyến Mãi:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Thời Gian:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Ngày:");

        cb_ctkm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bt_tk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_tk.setForeground(new java.awt.Color(0, 153, 153));
        bt_tk.setText("Tìm Kiếm");
        bt_tk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tkActionPerformed(evt);
            }
        });

        bt_lm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_lm.setForeground(new java.awt.Color(0, 153, 153));
        bt_lm.setText("Làm Mới");
        bt_lm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_lmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(bt_tk)
                        .addGap(145, 145, 145)
                        .addComponent(bt_lm))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addComponent(jLabel4))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_masp, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_madh, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_tennv, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_thoigian, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_ctkm, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cb_makh, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cb_madh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(cb_ctkm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_thoigian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_masp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cb_tennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cb_makh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tf_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_tk, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_lm, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        j_dathang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(j_dathang);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_tkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tkActionPerformed
        tblModel.getDataVector().removeAllElements();
        String s1 = (String) cb_madh.getSelectedItem();
        String s2 = (String) cb_masp.getSelectedItem();
        String s3 = (String) cb_makh.getSelectedItem();
        String s4 = (String) cb_ctkm.getSelectedItem();
        String s5 = tf_ngay.getText().trim();
        String s6 = tf_thoigian.getText().trim();
        String s7 = (String) cb_tennv.getSelectedItem();
        
            //lbDateError.setText("");
        
        
        String ss = "select * from qlqcf.chitietdathang join dathang on chitietdathang.MaDH=dathang.MaDH where chitietdathang.MaDH LIKE ? and chitietdathang.MaSP LIKE ? and chitietdathang.TenKH LIKE ? and chitietdathang.TenKM LIKE ? and dathang.NgayDH LIKE ? and dathang.ThoiGian LIKE ? and dathang.SoTaiKhoan LIKE ? Order by chitietdathang.MaDH DESC";
        try {
            ps = con.prepareStatement(ss);
            if (cb_madh.getSelectedIndex() == -1) {
                ps.setString(1, "%");
            } else {
                ps.setString(1, s1);
            }
            if (cb_masp.getSelectedIndex() == -1) {
                ps.setString(2, "%");
            } else {
                ps.setString(2, s2);
            }
            if (cb_makh.getSelectedIndex() == -1) {
                ps.setString(3, "%");
            } else {
                ps.setString(3, s3);
            }
            if (cb_ctkm.getSelectedIndex() == -1) {
                ps.setString(4, "%");
            } else {
                ps.setString(4, s4);
            }
            if (tf_ngay.getText().trim().equals("")) {
                ps.setString(5, "%");
            } else {
                ps.setString(5, "%" + s5);
            }
            if (tf_thoigian.getText().trim().equals("")) {
                ps.setString(6, "%");
            } else {
                ps.setString(6, s6 + "%");
            }
            if (cb_tennv.getSelectedIndex() == -1) {
                ps.setString(7, "%");
            } else {
                ps.setString(7, s7);
            }
            rsSearch1 = ps.executeQuery();
            if (rsSearch1.next()) {
                ps = con.prepareStatement(ss);
                if (cb_madh.getSelectedIndex() == -1) {
                    ps.setString(1, "%");
                } else {
                    ps.setString(1, s1);
                }
                if (cb_masp.getSelectedIndex() == -1) {
                    ps.setString(2, "%");
                } else {
                    ps.setString(2, s2);
                }
                if (cb_makh.getSelectedIndex() == -1) {
                    ps.setString(3, "%");
                } else {
                    ps.setString(3, s3);
                }
                if (cb_ctkm.getSelectedIndex() == -1) {
                    ps.setString(4, "%");
                } else {
                    ps.setString(4, s4);
                }
                if (tf_ngay.getText().trim().equals("")) {
                    ps.setString(5, "%");
                } else {
                    ps.setString(5, "%" + s5);
                }
                if (tf_thoigian.getText().trim().equals("")) {
                    ps.setString(6, "%");
                } else {
                    ps.setString(6, s6 + "%");
                }
                if (cb_tennv.getSelectedIndex() == -1) {
                    ps.setString(7, "%");
                } else {
                    ps.setString(7, s7);
                }
                rsSearch2 = ps.executeQuery();
                while (rsSearch2.next()) {
                    rowSearch = new Vector();
                    rowSearch.add(rsSearch2.getString("MaDH"));
                    rowSearch.add(rsSearch2.getString("MaSP"));
                    rowSearch.add(rsSearch2.getString("TenKH"));
                    rowSearch.add(rsSearch2.getString("SoLuong"));
                    rowSearch.add(rsSearch2.getString("TenKM"));
                    rowSearch.add(rsSearch2.getString("ThoiGian"));
                    rowSearch.add(rsSearch2.getString("NgayDH"));
                    rowSearch.add(rsSearch2.getString("SoTaiKhoan"));
                    tblModel.addRow(rowSearch);
                }
                j_dathang.setModel(tblModel);
            } else {
                JOptionPane.showMessageDialog(null, "Không tìm thấy dữ liệu.");
               bt_lmActionPerformed(evt);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Lỗi:: Không thể kết nối đến máy chủ");
        }
    }//GEN-LAST:event_bt_tkActionPerformed

    private void bt_lmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_lmActionPerformed
       ReloadTable();
        cb_makh.setSelectedIndex(-1);
        cb_madh.setSelectedIndex(-1);
        cb_masp.setSelectedIndex(-1);
        cb_tennv.setSelectedIndex(-1);
        cb_ctkm.setSelectedIndex(-1);
        tf_thoigian.setText("");
        tf_ngay.setText("");
    }//GEN-LAST:event_bt_lmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TTDaHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TTDaHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TTDaHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TTDaHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TTDaHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_lm;
    private javax.swing.JButton bt_tk;
    private javax.swing.JComboBox<String> cb_ctkm;
    private javax.swing.JComboBox<String> cb_madh;
    private javax.swing.JComboBox<String> cb_makh;
    private javax.swing.JComboBox<String> cb_masp;
    private javax.swing.JComboBox<String> cb_tennv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable j_dathang;
    private javax.swing.JTextField tf_ngay;
    private javax.swing.JTextField tf_thoigian;
    // End of variables declaration//GEN-END:variables

    

   
}
